/*
 * This file is generated by jOOQ.
 */
package com.mtgjson.tables.records;


import com.mtgjson.tables.SetTranslations;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SetTranslationsRecord extends UpdatableRecordImpl<SetTranslationsRecord> implements Record4<Integer, String, String, String> {

    private static final long serialVersionUID = -1315023298;

    /**
     * Setter for <code>set_translations.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>set_translations.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>set_translations.language</code>.
     */
    public void setLanguage(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>set_translations.language</code>.
     */
    public String getLanguage() {
        return (String) get(1);
    }

    /**
     * Setter for <code>set_translations.setCode</code>.
     */
    public void setSetcode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>set_translations.setCode</code>.
     */
    public String getSetcode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>set_translations.translation</code>.
     */
    public void setTranslation(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>set_translations.translation</code>.
     */
    public String getTranslation() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return SetTranslations.SET_TRANSLATIONS.ID;
    }

    @Override
    public Field<String> field2() {
        return SetTranslations.SET_TRANSLATIONS.LANGUAGE;
    }

    @Override
    public Field<String> field3() {
        return SetTranslations.SET_TRANSLATIONS.SETCODE;
    }

    @Override
    public Field<String> field4() {
        return SetTranslations.SET_TRANSLATIONS.TRANSLATION;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getLanguage();
    }

    @Override
    public String component3() {
        return getSetcode();
    }

    @Override
    public String component4() {
        return getTranslation();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getLanguage();
    }

    @Override
    public String value3() {
        return getSetcode();
    }

    @Override
    public String value4() {
        return getTranslation();
    }

    @Override
    public SetTranslationsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public SetTranslationsRecord value2(String value) {
        setLanguage(value);
        return this;
    }

    @Override
    public SetTranslationsRecord value3(String value) {
        setSetcode(value);
        return this;
    }

    @Override
    public SetTranslationsRecord value4(String value) {
        setTranslation(value);
        return this;
    }

    @Override
    public SetTranslationsRecord values(Integer value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SetTranslationsRecord
     */
    public SetTranslationsRecord() {
        super(SetTranslations.SET_TRANSLATIONS);
    }

    /**
     * Create a detached, initialised SetTranslationsRecord
     */
    public SetTranslationsRecord(Integer id, String language, String setcode, String translation) {
        super(SetTranslations.SET_TRANSLATIONS);

        set(0, id);
        set(1, language);
        set(2, setcode);
        set(3, translation);
    }
}
