/*
 * This file is generated by jOOQ.
 */
package com.mtgjson.tables.records;


import com.mtgjson.tables.Tokens;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TokensRecord extends UpdatableRecordImpl<TokensRecord> {

    private static final long serialVersionUID = 1040441834;

    /**
     * Setter for <code>tokens.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>tokens.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>tokens.artist</code>.
     */
    public void setArtist(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tokens.artist</code>.
     */
    public String getArtist() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tokens.borderColor</code>.
     */
    public void setBordercolor(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>tokens.borderColor</code>.
     */
    public String getBordercolor() {
        return (String) get(2);
    }

    /**
     * Setter for <code>tokens.colorIdentity</code>.
     */
    public void setColoridentity(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>tokens.colorIdentity</code>.
     */
    public String getColoridentity() {
        return (String) get(3);
    }

    /**
     * Setter for <code>tokens.colorIndicator</code>.
     */
    public void setColorindicator(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>tokens.colorIndicator</code>.
     */
    public String getColorindicator() {
        return (String) get(4);
    }

    /**
     * Setter for <code>tokens.colors</code>.
     */
    public void setColors(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>tokens.colors</code>.
     */
    public String getColors() {
        return (String) get(5);
    }

    /**
     * Setter for <code>tokens.duelDeck</code>.
     */
    public void setDueldeck(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>tokens.duelDeck</code>.
     */
    public String getDueldeck() {
        return (String) get(6);
    }

    /**
     * Setter for <code>tokens.isOnlineOnly</code>.
     */
    public void setIsonlineonly(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>tokens.isOnlineOnly</code>.
     */
    public Integer getIsonlineonly() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>tokens.layout</code>.
     */
    public void setLayout(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>tokens.layout</code>.
     */
    public String getLayout() {
        return (String) get(8);
    }

    /**
     * Setter for <code>tokens.loyalty</code>.
     */
    public void setLoyalty(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>tokens.loyalty</code>.
     */
    public String getLoyalty() {
        return (String) get(9);
    }

    /**
     * Setter for <code>tokens.name</code>.
     */
    public void setName(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>tokens.name</code>.
     */
    public String getName() {
        return (String) get(10);
    }

    /**
     * Setter for <code>tokens.names</code>.
     */
    public void setNames(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>tokens.names</code>.
     */
    public String getNames() {
        return (String) get(11);
    }

    /**
     * Setter for <code>tokens.number</code>.
     */
    public void setNumber(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>tokens.number</code>.
     */
    public String getNumber() {
        return (String) get(12);
    }

    /**
     * Setter for <code>tokens.power</code>.
     */
    public void setPower(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>tokens.power</code>.
     */
    public String getPower() {
        return (String) get(13);
    }

    /**
     * Setter for <code>tokens.reverseRelated</code>.
     */
    public void setReverserelated(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>tokens.reverseRelated</code>.
     */
    public String getReverserelated() {
        return (String) get(14);
    }

    /**
     * Setter for <code>tokens.scryfallId</code>.
     */
    public void setScryfallid(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>tokens.scryfallId</code>.
     */
    public String getScryfallid() {
        return (String) get(15);
    }

    /**
     * Setter for <code>tokens.scryfallIllustrationId</code>.
     */
    public void setScryfallillustrationid(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>tokens.scryfallIllustrationId</code>.
     */
    public String getScryfallillustrationid() {
        return (String) get(16);
    }

    /**
     * Setter for <code>tokens.scryfallOracleId</code>.
     */
    public void setScryfalloracleid(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>tokens.scryfallOracleId</code>.
     */
    public String getScryfalloracleid() {
        return (String) get(17);
    }

    /**
     * Setter for <code>tokens.setCode</code>.
     */
    public void setSetcode(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>tokens.setCode</code>.
     */
    public String getSetcode() {
        return (String) get(18);
    }

    /**
     * Setter for <code>tokens.side</code>.
     */
    public void setSide(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>tokens.side</code>.
     */
    public String getSide() {
        return (String) get(19);
    }

    /**
     * Setter for <code>tokens.subtypes</code>.
     */
    public void setSubtypes(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>tokens.subtypes</code>.
     */
    public String getSubtypes() {
        return (String) get(20);
    }

    /**
     * Setter for <code>tokens.supertypes</code>.
     */
    public void setSupertypes(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>tokens.supertypes</code>.
     */
    public String getSupertypes() {
        return (String) get(21);
    }

    /**
     * Setter for <code>tokens.text</code>.
     */
    public void setText(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>tokens.text</code>.
     */
    public String getText() {
        return (String) get(22);
    }

    /**
     * Setter for <code>tokens.toughness</code>.
     */
    public void setToughness(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>tokens.toughness</code>.
     */
    public String getToughness() {
        return (String) get(23);
    }

    /**
     * Setter for <code>tokens.type</code>.
     */
    public void setType(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>tokens.type</code>.
     */
    public String getType() {
        return (String) get(24);
    }

    /**
     * Setter for <code>tokens.types</code>.
     */
    public void setTypes(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>tokens.types</code>.
     */
    public String getTypes() {
        return (String) get(25);
    }

    /**
     * Setter for <code>tokens.uuid</code>.
     */
    public void setUuid(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>tokens.uuid</code>.
     */
    public String getUuid() {
        return (String) get(26);
    }

    /**
     * Setter for <code>tokens.watermark</code>.
     */
    public void setWatermark(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>tokens.watermark</code>.
     */
    public String getWatermark() {
        return (String) get(27);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TokensRecord
     */
    public TokensRecord() {
        super(Tokens.TOKENS);
    }

    /**
     * Create a detached, initialised TokensRecord
     */
    public TokensRecord(Integer id, String artist, String bordercolor, String coloridentity, String colorindicator, String colors, String dueldeck, Integer isonlineonly, String layout, String loyalty, String name, String names, String number, String power, String reverserelated, String scryfallid, String scryfallillustrationid, String scryfalloracleid, String setcode, String side, String subtypes, String supertypes, String text, String toughness, String type, String types, String uuid, String watermark) {
        super(Tokens.TOKENS);

        set(0, id);
        set(1, artist);
        set(2, bordercolor);
        set(3, coloridentity);
        set(4, colorindicator);
        set(5, colors);
        set(6, dueldeck);
        set(7, isonlineonly);
        set(8, layout);
        set(9, loyalty);
        set(10, name);
        set(11, names);
        set(12, number);
        set(13, power);
        set(14, reverserelated);
        set(15, scryfallid);
        set(16, scryfallillustrationid);
        set(17, scryfalloracleid);
        set(18, setcode);
        set(19, side);
        set(20, subtypes);
        set(21, supertypes);
        set(22, text);
        set(23, toughness);
        set(24, type);
        set(25, types);
        set(26, uuid);
        set(27, watermark);
    }
}
