/*
 * This file is generated by jOOQ.
 */
package org.krosanavengers.mtg.jooq.h2.public_;


import javax.annotation.Generated;

import org.krosanavengers.mtg.jooq.h2.public_.tables.Cardnonstaticabilities;
import org.krosanavengers.mtg.jooq.h2.public_.tables.Cards;
import org.krosanavengers.mtg.jooq.h2.public_.tables.Cardstaticabilities;
import org.krosanavengers.mtg.jooq.h2.public_.tables.Cardsubtypes;
import org.krosanavengers.mtg.jooq.h2.public_.tables.Cardsupertypes;
import org.krosanavengers.mtg.jooq.h2.public_.tables.Cardtypes;
import org.krosanavengers.mtg.jooq.h2.public_.tables.Nonstaticabilities;
import org.krosanavengers.mtg.jooq.h2.public_.tables.Staticabilities;
import org.krosanavengers.mtg.jooq.h2.public_.tables.Subtypes;
import org.krosanavengers.mtg.jooq.h2.public_.tables.Supertypes;
import org.krosanavengers.mtg.jooq.h2.public_.tables.Types;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.CARDNONSTATICABILITIES</code>.
     */
    public static final Cardnonstaticabilities CARDNONSTATICABILITIES = Cardnonstaticabilities.CARDNONSTATICABILITIES;

    /**
     * The table <code>PUBLIC.CARDS</code>.
     */
    public static final Cards CARDS = Cards.CARDS;

    /**
     * The table <code>PUBLIC.CARDSTATICABILITIES</code>.
     */
    public static final Cardstaticabilities CARDSTATICABILITIES = Cardstaticabilities.CARDSTATICABILITIES;

    /**
     * The table <code>PUBLIC.CARDSUBTYPES</code>.
     */
    public static final Cardsubtypes CARDSUBTYPES = Cardsubtypes.CARDSUBTYPES;

    /**
     * The table <code>PUBLIC.CARDSUPERTYPES</code>.
     */
    public static final Cardsupertypes CARDSUPERTYPES = Cardsupertypes.CARDSUPERTYPES;

    /**
     * The table <code>PUBLIC.CARDTYPES</code>.
     */
    public static final Cardtypes CARDTYPES = Cardtypes.CARDTYPES;

    /**
     * The table <code>PUBLIC.NONSTATICABILITIES</code>.
     */
    public static final Nonstaticabilities NONSTATICABILITIES = Nonstaticabilities.NONSTATICABILITIES;

    /**
     * The table <code>PUBLIC.STATICABILITIES</code>.
     */
    public static final Staticabilities STATICABILITIES = Staticabilities.STATICABILITIES;

    /**
     * The table <code>PUBLIC.SUBTYPES</code>.
     */
    public static final Subtypes SUBTYPES = Subtypes.SUBTYPES;

    /**
     * The table <code>PUBLIC.SUPERTYPES</code>.
     */
    public static final Supertypes SUPERTYPES = Supertypes.SUPERTYPES;

    /**
     * The table <code>PUBLIC.TYPES</code>.
     */
    public static final Types TYPES = Types.TYPES;
}
