/*
 * This file is generated by jOOQ.
 */
package com.cards.public_;


import com.cards.public_.tables.Cardnonstaticabilities;
import com.cards.public_.tables.Cards;
import com.cards.public_.tables.Cardstaticabilities;
import com.cards.public_.tables.Cardsubtypes;
import com.cards.public_.tables.Cardsupertypes;
import com.cards.public_.tables.Cardtypes;
import com.cards.public_.tables.Nonstaticabilities;
import com.cards.public_.tables.Staticabilities;
import com.cards.public_.tables.Subtypes;
import com.cards.public_.tables.Supertypes;
import com.cards.public_.tables.Types;
import com.cards.public_.tables.records.CardnonstaticabilitiesRecord;
import com.cards.public_.tables.records.CardsRecord;
import com.cards.public_.tables.records.CardstaticabilitiesRecord;
import com.cards.public_.tables.records.CardsubtypesRecord;
import com.cards.public_.tables.records.CardsupertypesRecord;
import com.cards.public_.tables.records.CardtypesRecord;
import com.cards.public_.tables.records.NonstaticabilitiesRecord;
import com.cards.public_.tables.records.StaticabilitiesRecord;
import com.cards.public_.tables.records.SubtypesRecord;
import com.cards.public_.tables.records.SupertypesRecord;
import com.cards.public_.tables.records.TypesRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<CardnonstaticabilitiesRecord, Long> IDENTITY_CARDNONSTATICABILITIES = Identities0.IDENTITY_CARDNONSTATICABILITIES;
    public static final Identity<CardsRecord, Long> IDENTITY_CARDS = Identities0.IDENTITY_CARDS;
    public static final Identity<CardstaticabilitiesRecord, Long> IDENTITY_CARDSTATICABILITIES = Identities0.IDENTITY_CARDSTATICABILITIES;
    public static final Identity<CardsubtypesRecord, Long> IDENTITY_CARDSUBTYPES = Identities0.IDENTITY_CARDSUBTYPES;
    public static final Identity<CardsupertypesRecord, Long> IDENTITY_CARDSUPERTYPES = Identities0.IDENTITY_CARDSUPERTYPES;
    public static final Identity<CardtypesRecord, Long> IDENTITY_CARDTYPES = Identities0.IDENTITY_CARDTYPES;
    public static final Identity<NonstaticabilitiesRecord, Long> IDENTITY_NONSTATICABILITIES = Identities0.IDENTITY_NONSTATICABILITIES;
    public static final Identity<StaticabilitiesRecord, Long> IDENTITY_STATICABILITIES = Identities0.IDENTITY_STATICABILITIES;
    public static final Identity<SubtypesRecord, Long> IDENTITY_SUBTYPES = Identities0.IDENTITY_SUBTYPES;
    public static final Identity<SupertypesRecord, Long> IDENTITY_SUPERTYPES = Identities0.IDENTITY_SUPERTYPES;
    public static final Identity<TypesRecord, Long> IDENTITY_TYPES = Identities0.IDENTITY_TYPES;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CardnonstaticabilitiesRecord> CONSTRAINT_8 = UniqueKeys0.CONSTRAINT_8;
    public static final UniqueKey<CardsRecord> CONSTRAINT_3 = UniqueKeys0.CONSTRAINT_3;
    public static final UniqueKey<CardsRecord> CONSTRAINT_3C = UniqueKeys0.CONSTRAINT_3C;
    public static final UniqueKey<CardstaticabilitiesRecord> CONSTRAINT_3F = UniqueKeys0.CONSTRAINT_3F;
    public static final UniqueKey<CardsubtypesRecord> CONSTRAINT_2 = UniqueKeys0.CONSTRAINT_2;
    public static final UniqueKey<CardsupertypesRecord> CONSTRAINT_6 = UniqueKeys0.CONSTRAINT_6;
    public static final UniqueKey<CardtypesRecord> CONSTRAINT_9 = UniqueKeys0.CONSTRAINT_9;
    public static final UniqueKey<NonstaticabilitiesRecord> CONSTRAINT_4 = UniqueKeys0.CONSTRAINT_4;
    public static final UniqueKey<NonstaticabilitiesRecord> CONSTRAINT_45 = UniqueKeys0.CONSTRAINT_45;
    public static final UniqueKey<StaticabilitiesRecord> CONSTRAINT_C = UniqueKeys0.CONSTRAINT_C;
    public static final UniqueKey<StaticabilitiesRecord> CONSTRAINT_C1 = UniqueKeys0.CONSTRAINT_C1;
    public static final UniqueKey<StaticabilitiesRecord> CONSTRAINT_C1D = UniqueKeys0.CONSTRAINT_C1D;
    public static final UniqueKey<SubtypesRecord> CONSTRAINT_B3 = UniqueKeys0.CONSTRAINT_B3;
    public static final UniqueKey<SubtypesRecord> CONSTRAINT_B3D = UniqueKeys0.CONSTRAINT_B3D;
    public static final UniqueKey<SupertypesRecord> CONSTRAINT_B = UniqueKeys0.CONSTRAINT_B;
    public static final UniqueKey<SupertypesRecord> CONSTRAINT_B7 = UniqueKeys0.CONSTRAINT_B7;
    public static final UniqueKey<TypesRecord> CONSTRAINT_4C = UniqueKeys0.CONSTRAINT_4C;
    public static final UniqueKey<TypesRecord> CONSTRAINT_4C9 = UniqueKeys0.CONSTRAINT_4C9;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<CardnonstaticabilitiesRecord, NonstaticabilitiesRecord> CONSTRAINT_80 = ForeignKeys0.CONSTRAINT_80;
    public static final ForeignKey<CardnonstaticabilitiesRecord, CardsRecord> CONSTRAINT_801 = ForeignKeys0.CONSTRAINT_801;
    public static final ForeignKey<CardstaticabilitiesRecord, StaticabilitiesRecord> CONSTRAINT_3FA = ForeignKeys0.CONSTRAINT_3FA;
    public static final ForeignKey<CardstaticabilitiesRecord, CardsRecord> CONSTRAINT_3FA3 = ForeignKeys0.CONSTRAINT_3FA3;
    public static final ForeignKey<CardsubtypesRecord, SubtypesRecord> CONSTRAINT_27 = ForeignKeys0.CONSTRAINT_27;
    public static final ForeignKey<CardsubtypesRecord, CardsRecord> CONSTRAINT_271 = ForeignKeys0.CONSTRAINT_271;
    public static final ForeignKey<CardsupertypesRecord, SupertypesRecord> CONSTRAINT_67 = ForeignKeys0.CONSTRAINT_67;
    public static final ForeignKey<CardsupertypesRecord, CardsRecord> CONSTRAINT_67A = ForeignKeys0.CONSTRAINT_67A;
    public static final ForeignKey<CardtypesRecord, TypesRecord> CONSTRAINT_98 = ForeignKeys0.CONSTRAINT_98;
    public static final ForeignKey<CardtypesRecord, CardsRecord> CONSTRAINT_98A = ForeignKeys0.CONSTRAINT_98A;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<CardnonstaticabilitiesRecord, Long> IDENTITY_CARDNONSTATICABILITIES = Internal.createIdentity(Cardnonstaticabilities.CARDNONSTATICABILITIES, Cardnonstaticabilities.CARDNONSTATICABILITIES.ID);
        public static Identity<CardsRecord, Long> IDENTITY_CARDS = Internal.createIdentity(Cards.CARDS, Cards.CARDS.ID);
        public static Identity<CardstaticabilitiesRecord, Long> IDENTITY_CARDSTATICABILITIES = Internal.createIdentity(Cardstaticabilities.CARDSTATICABILITIES, Cardstaticabilities.CARDSTATICABILITIES.ID);
        public static Identity<CardsubtypesRecord, Long> IDENTITY_CARDSUBTYPES = Internal.createIdentity(Cardsubtypes.CARDSUBTYPES, Cardsubtypes.CARDSUBTYPES.ID);
        public static Identity<CardsupertypesRecord, Long> IDENTITY_CARDSUPERTYPES = Internal.createIdentity(Cardsupertypes.CARDSUPERTYPES, Cardsupertypes.CARDSUPERTYPES.ID);
        public static Identity<CardtypesRecord, Long> IDENTITY_CARDTYPES = Internal.createIdentity(Cardtypes.CARDTYPES, Cardtypes.CARDTYPES.ID);
        public static Identity<NonstaticabilitiesRecord, Long> IDENTITY_NONSTATICABILITIES = Internal.createIdentity(Nonstaticabilities.NONSTATICABILITIES, Nonstaticabilities.NONSTATICABILITIES.ID);
        public static Identity<StaticabilitiesRecord, Long> IDENTITY_STATICABILITIES = Internal.createIdentity(Staticabilities.STATICABILITIES, Staticabilities.STATICABILITIES.ID);
        public static Identity<SubtypesRecord, Long> IDENTITY_SUBTYPES = Internal.createIdentity(Subtypes.SUBTYPES, Subtypes.SUBTYPES.ID);
        public static Identity<SupertypesRecord, Long> IDENTITY_SUPERTYPES = Internal.createIdentity(Supertypes.SUPERTYPES, Supertypes.SUPERTYPES.ID);
        public static Identity<TypesRecord, Long> IDENTITY_TYPES = Internal.createIdentity(Types.TYPES, Types.TYPES.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<CardnonstaticabilitiesRecord> CONSTRAINT_8 = Internal.createUniqueKey(Cardnonstaticabilities.CARDNONSTATICABILITIES, "CONSTRAINT_8", Cardnonstaticabilities.CARDNONSTATICABILITIES.ID);
        public static final UniqueKey<CardsRecord> CONSTRAINT_3 = Internal.createUniqueKey(Cards.CARDS, "CONSTRAINT_3", Cards.CARDS.ID);
        public static final UniqueKey<CardsRecord> CONSTRAINT_3C = Internal.createUniqueKey(Cards.CARDS, "CONSTRAINT_3C", Cards.CARDS.NAME);
        public static final UniqueKey<CardstaticabilitiesRecord> CONSTRAINT_3F = Internal.createUniqueKey(Cardstaticabilities.CARDSTATICABILITIES, "CONSTRAINT_3F", Cardstaticabilities.CARDSTATICABILITIES.ID);
        public static final UniqueKey<CardsubtypesRecord> CONSTRAINT_2 = Internal.createUniqueKey(Cardsubtypes.CARDSUBTYPES, "CONSTRAINT_2", Cardsubtypes.CARDSUBTYPES.ID);
        public static final UniqueKey<CardsupertypesRecord> CONSTRAINT_6 = Internal.createUniqueKey(Cardsupertypes.CARDSUPERTYPES, "CONSTRAINT_6", Cardsupertypes.CARDSUPERTYPES.ID);
        public static final UniqueKey<CardtypesRecord> CONSTRAINT_9 = Internal.createUniqueKey(Cardtypes.CARDTYPES, "CONSTRAINT_9", Cardtypes.CARDTYPES.ID);
        public static final UniqueKey<NonstaticabilitiesRecord> CONSTRAINT_4 = Internal.createUniqueKey(Nonstaticabilities.NONSTATICABILITIES, "CONSTRAINT_4", Nonstaticabilities.NONSTATICABILITIES.ID);
        public static final UniqueKey<NonstaticabilitiesRecord> CONSTRAINT_45 = Internal.createUniqueKey(Nonstaticabilities.NONSTATICABILITIES, "CONSTRAINT_45", Nonstaticabilities.NONSTATICABILITIES.TEXT);
        public static final UniqueKey<StaticabilitiesRecord> CONSTRAINT_C = Internal.createUniqueKey(Staticabilities.STATICABILITIES, "CONSTRAINT_C", Staticabilities.STATICABILITIES.ID);
        public static final UniqueKey<StaticabilitiesRecord> CONSTRAINT_C1 = Internal.createUniqueKey(Staticabilities.STATICABILITIES, "CONSTRAINT_C1", Staticabilities.STATICABILITIES.NAME);
        public static final UniqueKey<StaticabilitiesRecord> CONSTRAINT_C1D = Internal.createUniqueKey(Staticabilities.STATICABILITIES, "CONSTRAINT_C1D", Staticabilities.STATICABILITIES.TEXT);
        public static final UniqueKey<SubtypesRecord> CONSTRAINT_B3 = Internal.createUniqueKey(Subtypes.SUBTYPES, "CONSTRAINT_B3", Subtypes.SUBTYPES.ID);
        public static final UniqueKey<SubtypesRecord> CONSTRAINT_B3D = Internal.createUniqueKey(Subtypes.SUBTYPES, "CONSTRAINT_B3D", Subtypes.SUBTYPES.NAME);
        public static final UniqueKey<SupertypesRecord> CONSTRAINT_B = Internal.createUniqueKey(Supertypes.SUPERTYPES, "CONSTRAINT_B", Supertypes.SUPERTYPES.ID);
        public static final UniqueKey<SupertypesRecord> CONSTRAINT_B7 = Internal.createUniqueKey(Supertypes.SUPERTYPES, "CONSTRAINT_B7", Supertypes.SUPERTYPES.NAME);
        public static final UniqueKey<TypesRecord> CONSTRAINT_4C = Internal.createUniqueKey(Types.TYPES, "CONSTRAINT_4C", Types.TYPES.ID);
        public static final UniqueKey<TypesRecord> CONSTRAINT_4C9 = Internal.createUniqueKey(Types.TYPES, "CONSTRAINT_4C9", Types.TYPES.NAME);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<CardnonstaticabilitiesRecord, NonstaticabilitiesRecord> CONSTRAINT_80 = Internal.createForeignKey(com.cards.public_.Keys.CONSTRAINT_4, Cardnonstaticabilities.CARDNONSTATICABILITIES, "CONSTRAINT_80", Cardnonstaticabilities.CARDNONSTATICABILITIES.NONSTATICABILITY);
        public static final ForeignKey<CardnonstaticabilitiesRecord, CardsRecord> CONSTRAINT_801 = Internal.createForeignKey(com.cards.public_.Keys.CONSTRAINT_3, Cardnonstaticabilities.CARDNONSTATICABILITIES, "CONSTRAINT_801", Cardnonstaticabilities.CARDNONSTATICABILITIES.CARD);
        public static final ForeignKey<CardstaticabilitiesRecord, StaticabilitiesRecord> CONSTRAINT_3FA = Internal.createForeignKey(com.cards.public_.Keys.CONSTRAINT_C, Cardstaticabilities.CARDSTATICABILITIES, "CONSTRAINT_3FA", Cardstaticabilities.CARDSTATICABILITIES.STATICABILITY);
        public static final ForeignKey<CardstaticabilitiesRecord, CardsRecord> CONSTRAINT_3FA3 = Internal.createForeignKey(com.cards.public_.Keys.CONSTRAINT_3, Cardstaticabilities.CARDSTATICABILITIES, "CONSTRAINT_3FA3", Cardstaticabilities.CARDSTATICABILITIES.CARD);
        public static final ForeignKey<CardsubtypesRecord, SubtypesRecord> CONSTRAINT_27 = Internal.createForeignKey(com.cards.public_.Keys.CONSTRAINT_B3, Cardsubtypes.CARDSUBTYPES, "CONSTRAINT_27", Cardsubtypes.CARDSUBTYPES.SUBTYPE);
        public static final ForeignKey<CardsubtypesRecord, CardsRecord> CONSTRAINT_271 = Internal.createForeignKey(com.cards.public_.Keys.CONSTRAINT_3, Cardsubtypes.CARDSUBTYPES, "CONSTRAINT_271", Cardsubtypes.CARDSUBTYPES.CARD);
        public static final ForeignKey<CardsupertypesRecord, SupertypesRecord> CONSTRAINT_67 = Internal.createForeignKey(com.cards.public_.Keys.CONSTRAINT_B, Cardsupertypes.CARDSUPERTYPES, "CONSTRAINT_67", Cardsupertypes.CARDSUPERTYPES.SUPERTYPE);
        public static final ForeignKey<CardsupertypesRecord, CardsRecord> CONSTRAINT_67A = Internal.createForeignKey(com.cards.public_.Keys.CONSTRAINT_3, Cardsupertypes.CARDSUPERTYPES, "CONSTRAINT_67A", Cardsupertypes.CARDSUPERTYPES.CARD);
        public static final ForeignKey<CardtypesRecord, TypesRecord> CONSTRAINT_98 = Internal.createForeignKey(com.cards.public_.Keys.CONSTRAINT_4C, Cardtypes.CARDTYPES, "CONSTRAINT_98", Cardtypes.CARDTYPES.TYPE);
        public static final ForeignKey<CardtypesRecord, CardsRecord> CONSTRAINT_98A = Internal.createForeignKey(com.cards.public_.Keys.CONSTRAINT_3, Cardtypes.CARDTYPES, "CONSTRAINT_98A", Cardtypes.CARDTYPES.CARD);
    }
}
