/*
 * This file is generated by jOOQ.
 */
package com.cards.public_;


import com.cards.DefaultCatalog;
import com.cards.public_.tables.Cardnonstaticabilities;
import com.cards.public_.tables.Cards;
import com.cards.public_.tables.Cardstaticabilities;
import com.cards.public_.tables.Cardsubtypes;
import com.cards.public_.tables.Cardsupertypes;
import com.cards.public_.tables.Cardtypes;
import com.cards.public_.tables.Nonstaticabilities;
import com.cards.public_.tables.Staticabilities;
import com.cards.public_.tables.Subtypes;
import com.cards.public_.tables.Supertypes;
import com.cards.public_.tables.Types;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -85147002;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.CARDNONSTATICABILITIES</code>.
     */
    public final Cardnonstaticabilities CARDNONSTATICABILITIES = com.cards.public_.tables.Cardnonstaticabilities.CARDNONSTATICABILITIES;

    /**
     * The table <code>PUBLIC.CARDS</code>.
     */
    public final Cards CARDS = com.cards.public_.tables.Cards.CARDS;

    /**
     * The table <code>PUBLIC.CARDSTATICABILITIES</code>.
     */
    public final Cardstaticabilities CARDSTATICABILITIES = com.cards.public_.tables.Cardstaticabilities.CARDSTATICABILITIES;

    /**
     * The table <code>PUBLIC.CARDSUBTYPES</code>.
     */
    public final Cardsubtypes CARDSUBTYPES = com.cards.public_.tables.Cardsubtypes.CARDSUBTYPES;

    /**
     * The table <code>PUBLIC.CARDSUPERTYPES</code>.
     */
    public final Cardsupertypes CARDSUPERTYPES = com.cards.public_.tables.Cardsupertypes.CARDSUPERTYPES;

    /**
     * The table <code>PUBLIC.CARDTYPES</code>.
     */
    public final Cardtypes CARDTYPES = com.cards.public_.tables.Cardtypes.CARDTYPES;

    /**
     * The table <code>PUBLIC.NONSTATICABILITIES</code>.
     */
    public final Nonstaticabilities NONSTATICABILITIES = com.cards.public_.tables.Nonstaticabilities.NONSTATICABILITIES;

    /**
     * The table <code>PUBLIC.STATICABILITIES</code>.
     */
    public final Staticabilities STATICABILITIES = com.cards.public_.tables.Staticabilities.STATICABILITIES;

    /**
     * The table <code>PUBLIC.SUBTYPES</code>.
     */
    public final Subtypes SUBTYPES = com.cards.public_.tables.Subtypes.SUBTYPES;

    /**
     * The table <code>PUBLIC.SUPERTYPES</code>.
     */
    public final Supertypes SUPERTYPES = com.cards.public_.tables.Supertypes.SUPERTYPES;

    /**
     * The table <code>PUBLIC.TYPES</code>.
     */
    public final Types TYPES = com.cards.public_.tables.Types.TYPES;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Cardnonstaticabilities.CARDNONSTATICABILITIES,
            Cards.CARDS,
            Cardstaticabilities.CARDSTATICABILITIES,
            Cardsubtypes.CARDSUBTYPES,
            Cardsupertypes.CARDSUPERTYPES,
            Cardtypes.CARDTYPES,
            Nonstaticabilities.NONSTATICABILITIES,
            Staticabilities.STATICABILITIES,
            Subtypes.SUBTYPES,
            Supertypes.SUPERTYPES,
            Types.TYPES);
    }
}
