/*
 * This file is generated by jOOQ.
 */
package com.cards.public_.tables;


import com.cards.public_.Indexes;
import com.cards.public_.Keys;
import com.cards.public_.Public;
import com.cards.public_.tables.records.CardtypesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cardtypes extends TableImpl<CardtypesRecord> {

    private static final long serialVersionUID = 1522972604;

    /**
     * The reference instance of <code>PUBLIC.CARDTYPES</code>
     */
    public static final Cardtypes CARDTYPES = new Cardtypes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CardtypesRecord> getRecordType() {
        return CardtypesRecord.class;
    }

    /**
     * The column <code>PUBLIC.CARDTYPES.ID</code>.
     */
    public final TableField<CardtypesRecord, Long> ID = createField(DSL.name("ID"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>PUBLIC.CARDTYPES.TYPE</code>.
     */
    public final TableField<CardtypesRecord, Long> TYPE = createField(DSL.name("TYPE"), org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>PUBLIC.CARDTYPES.CARD</code>.
     */
    public final TableField<CardtypesRecord, Long> CARD = createField(DSL.name("CARD"), org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>PUBLIC.CARDTYPES</code> table reference
     */
    public Cardtypes() {
        this(DSL.name("CARDTYPES"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.CARDTYPES</code> table reference
     */
    public Cardtypes(String alias) {
        this(DSL.name(alias), CARDTYPES);
    }

    /**
     * Create an aliased <code>PUBLIC.CARDTYPES</code> table reference
     */
    public Cardtypes(Name alias) {
        this(alias, CARDTYPES);
    }

    private Cardtypes(Name alias, Table<CardtypesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Cardtypes(Name alias, Table<CardtypesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Cardtypes(Table<O> child, ForeignKey<O, CardtypesRecord> key) {
        super(child, key, CARDTYPES);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CONSTRAINT_INDEX_9, Indexes.CONSTRAINT_INDEX_98, Indexes.PRIMARY_KEY_9);
    }

    @Override
    public Identity<CardtypesRecord, Long> getIdentity() {
        return Keys.IDENTITY_CARDTYPES;
    }

    @Override
    public UniqueKey<CardtypesRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_9;
    }

    @Override
    public List<UniqueKey<CardtypesRecord>> getKeys() {
        return Arrays.<UniqueKey<CardtypesRecord>>asList(Keys.CONSTRAINT_9);
    }

    @Override
    public List<ForeignKey<CardtypesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CardtypesRecord, ?>>asList(Keys.CONSTRAINT_98, Keys.CONSTRAINT_98A);
    }

    public Types types() {
        return new Types(this, Keys.CONSTRAINT_98);
    }

    public Cards cards() {
        return new Cards(this, Keys.CONSTRAINT_98A);
    }

    @Override
    public Cardtypes as(String alias) {
        return new Cardtypes(DSL.name(alias), this);
    }

    @Override
    public Cardtypes as(Name alias) {
        return new Cardtypes(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Cardtypes rename(String name) {
        return new Cardtypes(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Cardtypes rename(Name name) {
        return new Cardtypes(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
