/*
 * This file is generated by jOOQ.
 */
package com.cards.public_.tables;


import com.cards.public_.Indexes;
import com.cards.public_.Keys;
import com.cards.public_.Public;
import com.cards.public_.tables.records.TypesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Types extends TableImpl<TypesRecord> {

    private static final long serialVersionUID = 571101861;

    /**
     * The reference instance of <code>PUBLIC.TYPES</code>
     */
    public static final Types TYPES = new Types();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TypesRecord> getRecordType() {
        return TypesRecord.class;
    }

    /**
     * The column <code>PUBLIC.TYPES.ID</code>.
     */
    public final TableField<TypesRecord, Long> ID = createField(DSL.name("ID"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>PUBLIC.TYPES.NAME</code>.
     */
    public final TableField<TypesRecord, String> NAME = createField(DSL.name("NAME"), org.jooq.impl.SQLDataType.VARCHAR(20), this, "");

    /**
     * Create a <code>PUBLIC.TYPES</code> table reference
     */
    public Types() {
        this(DSL.name("TYPES"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.TYPES</code> table reference
     */
    public Types(String alias) {
        this(DSL.name(alias), TYPES);
    }

    /**
     * Create an aliased <code>PUBLIC.TYPES</code> table reference
     */
    public Types(Name alias) {
        this(alias, TYPES);
    }

    private Types(Name alias, Table<TypesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Types(Name alias, Table<TypesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Types(Table<O> child, ForeignKey<O, TypesRecord> key) {
        super(child, key, TYPES);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CONSTRAINT_INDEX_4C, Indexes.PRIMARY_KEY_4C);
    }

    @Override
    public Identity<TypesRecord, Long> getIdentity() {
        return Keys.IDENTITY_TYPES;
    }

    @Override
    public UniqueKey<TypesRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_4C;
    }

    @Override
    public List<UniqueKey<TypesRecord>> getKeys() {
        return Arrays.<UniqueKey<TypesRecord>>asList(Keys.CONSTRAINT_4C, Keys.CONSTRAINT_4C9);
    }

    @Override
    public Types as(String alias) {
        return new Types(DSL.name(alias), this);
    }

    @Override
    public Types as(Name alias) {
        return new Types(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Types rename(String name) {
        return new Types(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Types rename(Name name) {
        return new Types(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
