/*
 * This file is generated by jOOQ.
 */
package org.krosanavengers.mtg.jooq.mtgjson.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Legalities implements Serializable {

    private static final long serialVersionUID = -137865721;

    private Integer id;
    private String  format;
    private String  status;
    private String  uuid;

    public Legalities() {}

    public Legalities(Legalities value) {
        this.id = value.id;
        this.format = value.format;
        this.status = value.status;
        this.uuid = value.uuid;
    }

    public Legalities(
        Integer id,
        String  format,
        String  status,
        String  uuid
    ) {
        this.id = id;
        this.format = format;
        this.status = status;
        this.uuid = uuid;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getFormat() {
        return this.format;
    }

    public void setFormat(String format) {
        this.format = format;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getUuid() {
        return this.uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Legalities (");

        sb.append(id);
        sb.append(", ").append(format);
        sb.append(", ").append(status);
        sb.append(", ").append(uuid);

        sb.append(")");
        return sb.toString();
    }
}
