/*
 * This file is generated by jOOQ.
 */
package org.krosanavengers.mtg.jooq.mtgjson.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sets implements Serializable {

    private static final long serialVersionUID = 1148093112;

    private Integer id;
    private Integer basesetsize;
    private String  block;
    private String  boosterv3;
    private String  code;
    private String  codev3;
    private Integer isfoilonly;
    private Integer isforeignonly;
    private Integer isonlineonly;
    private Integer ispartialpreview;
    private String  keyrunecode;
    private Integer mcmid;
    private String  mcmname;
    private String  meta;
    private String  mtgocode;
    private String  name;
    private String  parentcode;
    private String  releasedate;
    private Integer tcgplayergroupid;
    private Integer totalsetsize;
    private String  type;

    public Sets() {}

    public Sets(Sets value) {
        this.id = value.id;
        this.basesetsize = value.basesetsize;
        this.block = value.block;
        this.boosterv3 = value.boosterv3;
        this.code = value.code;
        this.codev3 = value.codev3;
        this.isfoilonly = value.isfoilonly;
        this.isforeignonly = value.isforeignonly;
        this.isonlineonly = value.isonlineonly;
        this.ispartialpreview = value.ispartialpreview;
        this.keyrunecode = value.keyrunecode;
        this.mcmid = value.mcmid;
        this.mcmname = value.mcmname;
        this.meta = value.meta;
        this.mtgocode = value.mtgocode;
        this.name = value.name;
        this.parentcode = value.parentcode;
        this.releasedate = value.releasedate;
        this.tcgplayergroupid = value.tcgplayergroupid;
        this.totalsetsize = value.totalsetsize;
        this.type = value.type;
    }

    public Sets(
        Integer id,
        Integer basesetsize,
        String  block,
        String  boosterv3,
        String  code,
        String  codev3,
        Integer isfoilonly,
        Integer isforeignonly,
        Integer isonlineonly,
        Integer ispartialpreview,
        String  keyrunecode,
        Integer mcmid,
        String  mcmname,
        String  meta,
        String  mtgocode,
        String  name,
        String  parentcode,
        String  releasedate,
        Integer tcgplayergroupid,
        Integer totalsetsize,
        String  type
    ) {
        this.id = id;
        this.basesetsize = basesetsize;
        this.block = block;
        this.boosterv3 = boosterv3;
        this.code = code;
        this.codev3 = codev3;
        this.isfoilonly = isfoilonly;
        this.isforeignonly = isforeignonly;
        this.isonlineonly = isonlineonly;
        this.ispartialpreview = ispartialpreview;
        this.keyrunecode = keyrunecode;
        this.mcmid = mcmid;
        this.mcmname = mcmname;
        this.meta = meta;
        this.mtgocode = mtgocode;
        this.name = name;
        this.parentcode = parentcode;
        this.releasedate = releasedate;
        this.tcgplayergroupid = tcgplayergroupid;
        this.totalsetsize = totalsetsize;
        this.type = type;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getBasesetsize() {
        return this.basesetsize;
    }

    public void setBasesetsize(Integer basesetsize) {
        this.basesetsize = basesetsize;
    }

    public String getBlock() {
        return this.block;
    }

    public void setBlock(String block) {
        this.block = block;
    }

    public String getBoosterv3() {
        return this.boosterv3;
    }

    public void setBoosterv3(String boosterv3) {
        this.boosterv3 = boosterv3;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getCodev3() {
        return this.codev3;
    }

    public void setCodev3(String codev3) {
        this.codev3 = codev3;
    }

    public Integer getIsfoilonly() {
        return this.isfoilonly;
    }

    public void setIsfoilonly(Integer isfoilonly) {
        this.isfoilonly = isfoilonly;
    }

    public Integer getIsforeignonly() {
        return this.isforeignonly;
    }

    public void setIsforeignonly(Integer isforeignonly) {
        this.isforeignonly = isforeignonly;
    }

    public Integer getIsonlineonly() {
        return this.isonlineonly;
    }

    public void setIsonlineonly(Integer isonlineonly) {
        this.isonlineonly = isonlineonly;
    }

    public Integer getIspartialpreview() {
        return this.ispartialpreview;
    }

    public void setIspartialpreview(Integer ispartialpreview) {
        this.ispartialpreview = ispartialpreview;
    }

    public String getKeyrunecode() {
        return this.keyrunecode;
    }

    public void setKeyrunecode(String keyrunecode) {
        this.keyrunecode = keyrunecode;
    }

    public Integer getMcmid() {
        return this.mcmid;
    }

    public void setMcmid(Integer mcmid) {
        this.mcmid = mcmid;
    }

    public String getMcmname() {
        return this.mcmname;
    }

    public void setMcmname(String mcmname) {
        this.mcmname = mcmname;
    }

    public String getMeta() {
        return this.meta;
    }

    public void setMeta(String meta) {
        this.meta = meta;
    }

    public String getMtgocode() {
        return this.mtgocode;
    }

    public void setMtgocode(String mtgocode) {
        this.mtgocode = mtgocode;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getParentcode() {
        return this.parentcode;
    }

    public void setParentcode(String parentcode) {
        this.parentcode = parentcode;
    }

    public String getReleasedate() {
        return this.releasedate;
    }

    public void setReleasedate(String releasedate) {
        this.releasedate = releasedate;
    }

    public Integer getTcgplayergroupid() {
        return this.tcgplayergroupid;
    }

    public void setTcgplayergroupid(Integer tcgplayergroupid) {
        this.tcgplayergroupid = tcgplayergroupid;
    }

    public Integer getTotalsetsize() {
        return this.totalsetsize;
    }

    public void setTotalsetsize(Integer totalsetsize) {
        this.totalsetsize = totalsetsize;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Sets (");

        sb.append(id);
        sb.append(", ").append(basesetsize);
        sb.append(", ").append(block);
        sb.append(", ").append(boosterv3);
        sb.append(", ").append(code);
        sb.append(", ").append(codev3);
        sb.append(", ").append(isfoilonly);
        sb.append(", ").append(isforeignonly);
        sb.append(", ").append(isonlineonly);
        sb.append(", ").append(ispartialpreview);
        sb.append(", ").append(keyrunecode);
        sb.append(", ").append(mcmid);
        sb.append(", ").append(mcmname);
        sb.append(", ").append(meta);
        sb.append(", ").append(mtgocode);
        sb.append(", ").append(name);
        sb.append(", ").append(parentcode);
        sb.append(", ").append(releasedate);
        sb.append(", ").append(tcgplayergroupid);
        sb.append(", ").append(totalsetsize);
        sb.append(", ").append(type);

        sb.append(")");
        return sb.toString();
    }
}
