/*
 * This file is generated by jOOQ.
 */
package org.krosanavengers.mtg.jooq.mtgjson.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SetTranslations implements Serializable {

    private static final long serialVersionUID = -544263351;

    private Integer id;
    private String  language;
    private String  setcode;
    private String  translation;

    public SetTranslations() {}

    public SetTranslations(SetTranslations value) {
        this.id = value.id;
        this.language = value.language;
        this.setcode = value.setcode;
        this.translation = value.translation;
    }

    public SetTranslations(
        Integer id,
        String  language,
        String  setcode,
        String  translation
    ) {
        this.id = id;
        this.language = language;
        this.setcode = setcode;
        this.translation = translation;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getLanguage() {
        return this.language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public String getSetcode() {
        return this.setcode;
    }

    public void setSetcode(String setcode) {
        this.setcode = setcode;
    }

    public String getTranslation() {
        return this.translation;
    }

    public void setTranslation(String translation) {
        this.translation = translation;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SetTranslations (");

        sb.append(id);
        sb.append(", ").append(language);
        sb.append(", ").append(setcode);
        sb.append(", ").append(translation);

        sb.append(")");
        return sb.toString();
    }
}
