/*
 * This file is generated by jOOQ.
 */
package org.krosanavengers.mtg.jooq.mtgjson;


import javax.annotation.Generated;

import org.krosanavengers.mtg.jooq.mtgjson.tables.Cards;
import org.krosanavengers.mtg.jooq.mtgjson.tables.ForeignData;
import org.krosanavengers.mtg.jooq.mtgjson.tables.Legalities;
import org.krosanavengers.mtg.jooq.mtgjson.tables.Prices;
import org.krosanavengers.mtg.jooq.mtgjson.tables.Rulings;
import org.krosanavengers.mtg.jooq.mtgjson.tables.SetTranslations;
import org.krosanavengers.mtg.jooq.mtgjson.tables.Sets;
import org.krosanavengers.mtg.jooq.mtgjson.tables.SqliteSequence;
import org.krosanavengers.mtg.jooq.mtgjson.tables.Tokens;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>cards</code>.
     */
    public static final Cards CARDS = Cards.CARDS;

    /**
     * The table <code>foreign_data</code>.
     */
    public static final ForeignData FOREIGN_DATA = ForeignData.FOREIGN_DATA;

    /**
     * The table <code>legalities</code>.
     */
    public static final Legalities LEGALITIES = Legalities.LEGALITIES;

    /**
     * The table <code>prices</code>.
     */
    public static final Prices PRICES = Prices.PRICES;

    /**
     * The table <code>rulings</code>.
     */
    public static final Rulings RULINGS = Rulings.RULINGS;

    /**
     * The table <code>set_translations</code>.
     */
    public static final SetTranslations SET_TRANSLATIONS = SetTranslations.SET_TRANSLATIONS;

    /**
     * The table <code>sets</code>.
     */
    public static final Sets SETS = Sets.SETS;

    /**
     * The table <code>sqlite_sequence</code>.
     */
    public static final SqliteSequence SQLITE_SEQUENCE = SqliteSequence.SQLITE_SEQUENCE;

    /**
     * The table <code>tokens</code>.
     */
    public static final Tokens TOKENS = Tokens.TOKENS;
}
