/*
 * This file is generated by jOOQ.
 */
package org.krosanavengers.mtg.jooq.h2.public_.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import org.krosanavengers.mtg.jooq.h2.public_.tables.Nonstaticabilities;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NonstaticabilitiesRecord extends UpdatableRecordImpl<NonstaticabilitiesRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = -863213220;

    /**
     * Setter for <code>PUBLIC.NONSTATICABILITIES.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.NONSTATICABILITIES.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.NONSTATICABILITIES.TEXT</code>.
     */
    public void setText(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.NONSTATICABILITIES.TEXT</code>.
     */
    public String getText() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Nonstaticabilities.NONSTATICABILITIES.ID;
    }

    @Override
    public Field<String> field2() {
        return Nonstaticabilities.NONSTATICABILITIES.TEXT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getText();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getText();
    }

    @Override
    public NonstaticabilitiesRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public NonstaticabilitiesRecord value2(String value) {
        setText(value);
        return this;
    }

    @Override
    public NonstaticabilitiesRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NonstaticabilitiesRecord
     */
    public NonstaticabilitiesRecord() {
        super(Nonstaticabilities.NONSTATICABILITIES);
    }

    /**
     * Create a detached, initialised NonstaticabilitiesRecord
     */
    public NonstaticabilitiesRecord(Long id, String text) {
        super(Nonstaticabilities.NONSTATICABILITIES);

        set(0, id);
        set(1, text);
    }
}
