/*
 * This file is generated by jOOQ.
 */
package org.krosanavengers.mtg.jooq.h2.public_.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.krosanavengers.mtg.jooq.h2.public_.tables.Staticabilities;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StaticabilitiesRecord extends UpdatableRecordImpl<StaticabilitiesRecord> implements Record3<Long, String, String> {

    private static final long serialVersionUID = 1305263287;

    /**
     * Setter for <code>PUBLIC.STATICABILITIES.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.STATICABILITIES.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.STATICABILITIES.NAME</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.STATICABILITIES.NAME</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.STATICABILITIES.TEXT</code>.
     */
    public void setText(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.STATICABILITIES.TEXT</code>.
     */
    public String getText() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Staticabilities.STATICABILITIES.ID;
    }

    @Override
    public Field<String> field2() {
        return Staticabilities.STATICABILITIES.NAME;
    }

    @Override
    public Field<String> field3() {
        return Staticabilities.STATICABILITIES.TEXT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getText();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getText();
    }

    @Override
    public StaticabilitiesRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public StaticabilitiesRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public StaticabilitiesRecord value3(String value) {
        setText(value);
        return this;
    }

    @Override
    public StaticabilitiesRecord values(Long value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StaticabilitiesRecord
     */
    public StaticabilitiesRecord() {
        super(Staticabilities.STATICABILITIES);
    }

    /**
     * Create a detached, initialised StaticabilitiesRecord
     */
    public StaticabilitiesRecord(Long id, String name, String text) {
        super(Staticabilities.STATICABILITIES);

        set(0, id);
        set(1, name);
        set(2, text);
    }
}
