/*
 * This file is generated by jOOQ.
 */
package org.krosanavengers.mtg.jooq.h2.public_.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import org.krosanavengers.mtg.jooq.h2.public_.tables.Subtypes;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SubtypesRecord extends UpdatableRecordImpl<SubtypesRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = 2146588064;

    /**
     * Setter for <code>PUBLIC.SUBTYPES.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.SUBTYPES.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.SUBTYPES.NAME</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.SUBTYPES.NAME</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Subtypes.SUBTYPES.ID;
    }

    @Override
    public Field<String> field2() {
        return Subtypes.SUBTYPES.NAME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public SubtypesRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SubtypesRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public SubtypesRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SubtypesRecord
     */
    public SubtypesRecord() {
        super(Subtypes.SUBTYPES);
    }

    /**
     * Create a detached, initialised SubtypesRecord
     */
    public SubtypesRecord(Long id, String name) {
        super(Subtypes.SUBTYPES);

        set(0, id);
        set(1, name);
    }
}
