/*
 * This file is generated by jOOQ.
 */
package com.mtgjson.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cards implements Serializable {

    private static final long serialVersionUID = -133736857;

    private Integer id;
    private String  artist;
    private String  bordercolor;
    private String  coloridentity;
    private String  colorindicator;
    private String  colors;
    private Float   convertedmanacost;
    private String  dueldeck;
    private String  edhrecrank;
    private Float   faceconvertedmanacost;
    private String  flavortext;
    private String  frameeffect;
    private String  frameeffects;
    private String  frameversion;
    private String  hand;
    private Integer hasfoil;
    private Integer hasnodecklimit;
    private Integer hasnonfoil;
    private Integer isalternative;
    private Integer isarena;
    private Integer isfullart;
    private Integer ismtgo;
    private Integer isonlineonly;
    private Integer isoversized;
    private Integer ispaper;
    private Integer ispromo;
    private Integer isreprint;
    private Integer isreserved;
    private Integer isstarter;
    private Integer isstoryspotlight;
    private Integer istextless;
    private Integer istimeshifted;
    private String  layout;
    private String  leadershipskills;
    private String  life;
    private String  loyalty;
    private String  manacost;
    private Integer mcmid;
    private Integer mcmmetaid;
    private String  mcmname;
    private Integer mtgarenaid;
    private Integer mtgofoilid;
    private Integer mtgoid;
    private Integer mtgstocksid;
    private Integer multiverseid;
    private String  name;
    private String  names;
    private String  number;
    private String  originaltext;
    private String  originaltype;
    private String  otherfaceids;
    private String  power;
    private String  printings;
    private String  purchaseurls;
    private String  rarity;
    private String  scryfallid;
    private String  scryfallillustrationid;
    private String  scryfalloracleid;
    private String  setcode;
    private String  side;
    private String  subtypes;
    private String  supertypes;
    private Integer tcgplayerproductid;
    private String  tcgplayerpurchaseurl;
    private String  text;
    private String  toughness;
    private String  type;
    private String  types;
    private String  uuid;
    private String  variations;
    private String  watermark;

    public Cards() {}

    public Cards(Cards value) {
        this.id = value.id;
        this.artist = value.artist;
        this.bordercolor = value.bordercolor;
        this.coloridentity = value.coloridentity;
        this.colorindicator = value.colorindicator;
        this.colors = value.colors;
        this.convertedmanacost = value.convertedmanacost;
        this.dueldeck = value.dueldeck;
        this.edhrecrank = value.edhrecrank;
        this.faceconvertedmanacost = value.faceconvertedmanacost;
        this.flavortext = value.flavortext;
        this.frameeffect = value.frameeffect;
        this.frameeffects = value.frameeffects;
        this.frameversion = value.frameversion;
        this.hand = value.hand;
        this.hasfoil = value.hasfoil;
        this.hasnodecklimit = value.hasnodecklimit;
        this.hasnonfoil = value.hasnonfoil;
        this.isalternative = value.isalternative;
        this.isarena = value.isarena;
        this.isfullart = value.isfullart;
        this.ismtgo = value.ismtgo;
        this.isonlineonly = value.isonlineonly;
        this.isoversized = value.isoversized;
        this.ispaper = value.ispaper;
        this.ispromo = value.ispromo;
        this.isreprint = value.isreprint;
        this.isreserved = value.isreserved;
        this.isstarter = value.isstarter;
        this.isstoryspotlight = value.isstoryspotlight;
        this.istextless = value.istextless;
        this.istimeshifted = value.istimeshifted;
        this.layout = value.layout;
        this.leadershipskills = value.leadershipskills;
        this.life = value.life;
        this.loyalty = value.loyalty;
        this.manacost = value.manacost;
        this.mcmid = value.mcmid;
        this.mcmmetaid = value.mcmmetaid;
        this.mcmname = value.mcmname;
        this.mtgarenaid = value.mtgarenaid;
        this.mtgofoilid = value.mtgofoilid;
        this.mtgoid = value.mtgoid;
        this.mtgstocksid = value.mtgstocksid;
        this.multiverseid = value.multiverseid;
        this.name = value.name;
        this.names = value.names;
        this.number = value.number;
        this.originaltext = value.originaltext;
        this.originaltype = value.originaltype;
        this.otherfaceids = value.otherfaceids;
        this.power = value.power;
        this.printings = value.printings;
        this.purchaseurls = value.purchaseurls;
        this.rarity = value.rarity;
        this.scryfallid = value.scryfallid;
        this.scryfallillustrationid = value.scryfallillustrationid;
        this.scryfalloracleid = value.scryfalloracleid;
        this.setcode = value.setcode;
        this.side = value.side;
        this.subtypes = value.subtypes;
        this.supertypes = value.supertypes;
        this.tcgplayerproductid = value.tcgplayerproductid;
        this.tcgplayerpurchaseurl = value.tcgplayerpurchaseurl;
        this.text = value.text;
        this.toughness = value.toughness;
        this.type = value.type;
        this.types = value.types;
        this.uuid = value.uuid;
        this.variations = value.variations;
        this.watermark = value.watermark;
    }

    public Cards(
        Integer id,
        String  artist,
        String  bordercolor,
        String  coloridentity,
        String  colorindicator,
        String  colors,
        Float   convertedmanacost,
        String  dueldeck,
        String  edhrecrank,
        Float   faceconvertedmanacost,
        String  flavortext,
        String  frameeffect,
        String  frameeffects,
        String  frameversion,
        String  hand,
        Integer hasfoil,
        Integer hasnodecklimit,
        Integer hasnonfoil,
        Integer isalternative,
        Integer isarena,
        Integer isfullart,
        Integer ismtgo,
        Integer isonlineonly,
        Integer isoversized,
        Integer ispaper,
        Integer ispromo,
        Integer isreprint,
        Integer isreserved,
        Integer isstarter,
        Integer isstoryspotlight,
        Integer istextless,
        Integer istimeshifted,
        String  layout,
        String  leadershipskills,
        String  life,
        String  loyalty,
        String  manacost,
        Integer mcmid,
        Integer mcmmetaid,
        String  mcmname,
        Integer mtgarenaid,
        Integer mtgofoilid,
        Integer mtgoid,
        Integer mtgstocksid,
        Integer multiverseid,
        String  name,
        String  names,
        String  number,
        String  originaltext,
        String  originaltype,
        String  otherfaceids,
        String  power,
        String  printings,
        String  purchaseurls,
        String  rarity,
        String  scryfallid,
        String  scryfallillustrationid,
        String  scryfalloracleid,
        String  setcode,
        String  side,
        String  subtypes,
        String  supertypes,
        Integer tcgplayerproductid,
        String  tcgplayerpurchaseurl,
        String  text,
        String  toughness,
        String  type,
        String  types,
        String  uuid,
        String  variations,
        String  watermark
    ) {
        this.id = id;
        this.artist = artist;
        this.bordercolor = bordercolor;
        this.coloridentity = coloridentity;
        this.colorindicator = colorindicator;
        this.colors = colors;
        this.convertedmanacost = convertedmanacost;
        this.dueldeck = dueldeck;
        this.edhrecrank = edhrecrank;
        this.faceconvertedmanacost = faceconvertedmanacost;
        this.flavortext = flavortext;
        this.frameeffect = frameeffect;
        this.frameeffects = frameeffects;
        this.frameversion = frameversion;
        this.hand = hand;
        this.hasfoil = hasfoil;
        this.hasnodecklimit = hasnodecklimit;
        this.hasnonfoil = hasnonfoil;
        this.isalternative = isalternative;
        this.isarena = isarena;
        this.isfullart = isfullart;
        this.ismtgo = ismtgo;
        this.isonlineonly = isonlineonly;
        this.isoversized = isoversized;
        this.ispaper = ispaper;
        this.ispromo = ispromo;
        this.isreprint = isreprint;
        this.isreserved = isreserved;
        this.isstarter = isstarter;
        this.isstoryspotlight = isstoryspotlight;
        this.istextless = istextless;
        this.istimeshifted = istimeshifted;
        this.layout = layout;
        this.leadershipskills = leadershipskills;
        this.life = life;
        this.loyalty = loyalty;
        this.manacost = manacost;
        this.mcmid = mcmid;
        this.mcmmetaid = mcmmetaid;
        this.mcmname = mcmname;
        this.mtgarenaid = mtgarenaid;
        this.mtgofoilid = mtgofoilid;
        this.mtgoid = mtgoid;
        this.mtgstocksid = mtgstocksid;
        this.multiverseid = multiverseid;
        this.name = name;
        this.names = names;
        this.number = number;
        this.originaltext = originaltext;
        this.originaltype = originaltype;
        this.otherfaceids = otherfaceids;
        this.power = power;
        this.printings = printings;
        this.purchaseurls = purchaseurls;
        this.rarity = rarity;
        this.scryfallid = scryfallid;
        this.scryfallillustrationid = scryfallillustrationid;
        this.scryfalloracleid = scryfalloracleid;
        this.setcode = setcode;
        this.side = side;
        this.subtypes = subtypes;
        this.supertypes = supertypes;
        this.tcgplayerproductid = tcgplayerproductid;
        this.tcgplayerpurchaseurl = tcgplayerpurchaseurl;
        this.text = text;
        this.toughness = toughness;
        this.type = type;
        this.types = types;
        this.uuid = uuid;
        this.variations = variations;
        this.watermark = watermark;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getArtist() {
        return this.artist;
    }

    public void setArtist(String artist) {
        this.artist = artist;
    }

    public String getBordercolor() {
        return this.bordercolor;
    }

    public void setBordercolor(String bordercolor) {
        this.bordercolor = bordercolor;
    }

    public String getColoridentity() {
        return this.coloridentity;
    }

    public void setColoridentity(String coloridentity) {
        this.coloridentity = coloridentity;
    }

    public String getColorindicator() {
        return this.colorindicator;
    }

    public void setColorindicator(String colorindicator) {
        this.colorindicator = colorindicator;
    }

    public String getColors() {
        return this.colors;
    }

    public void setColors(String colors) {
        this.colors = colors;
    }

    public Float getConvertedmanacost() {
        return this.convertedmanacost;
    }

    public void setConvertedmanacost(Float convertedmanacost) {
        this.convertedmanacost = convertedmanacost;
    }

    public String getDueldeck() {
        return this.dueldeck;
    }

    public void setDueldeck(String dueldeck) {
        this.dueldeck = dueldeck;
    }

    public String getEdhrecrank() {
        return this.edhrecrank;
    }

    public void setEdhrecrank(String edhrecrank) {
        this.edhrecrank = edhrecrank;
    }

    public Float getFaceconvertedmanacost() {
        return this.faceconvertedmanacost;
    }

    public void setFaceconvertedmanacost(Float faceconvertedmanacost) {
        this.faceconvertedmanacost = faceconvertedmanacost;
    }

    public String getFlavortext() {
        return this.flavortext;
    }

    public void setFlavortext(String flavortext) {
        this.flavortext = flavortext;
    }

    public String getFrameeffect() {
        return this.frameeffect;
    }

    public void setFrameeffect(String frameeffect) {
        this.frameeffect = frameeffect;
    }

    public String getFrameeffects() {
        return this.frameeffects;
    }

    public void setFrameeffects(String frameeffects) {
        this.frameeffects = frameeffects;
    }

    public String getFrameversion() {
        return this.frameversion;
    }

    public void setFrameversion(String frameversion) {
        this.frameversion = frameversion;
    }

    public String getHand() {
        return this.hand;
    }

    public void setHand(String hand) {
        this.hand = hand;
    }

    public Integer getHasfoil() {
        return this.hasfoil;
    }

    public void setHasfoil(Integer hasfoil) {
        this.hasfoil = hasfoil;
    }

    public Integer getHasnodecklimit() {
        return this.hasnodecklimit;
    }

    public void setHasnodecklimit(Integer hasnodecklimit) {
        this.hasnodecklimit = hasnodecklimit;
    }

    public Integer getHasnonfoil() {
        return this.hasnonfoil;
    }

    public void setHasnonfoil(Integer hasnonfoil) {
        this.hasnonfoil = hasnonfoil;
    }

    public Integer getIsalternative() {
        return this.isalternative;
    }

    public void setIsalternative(Integer isalternative) {
        this.isalternative = isalternative;
    }

    public Integer getIsarena() {
        return this.isarena;
    }

    public void setIsarena(Integer isarena) {
        this.isarena = isarena;
    }

    public Integer getIsfullart() {
        return this.isfullart;
    }

    public void setIsfullart(Integer isfullart) {
        this.isfullart = isfullart;
    }

    public Integer getIsmtgo() {
        return this.ismtgo;
    }

    public void setIsmtgo(Integer ismtgo) {
        this.ismtgo = ismtgo;
    }

    public Integer getIsonlineonly() {
        return this.isonlineonly;
    }

    public void setIsonlineonly(Integer isonlineonly) {
        this.isonlineonly = isonlineonly;
    }

    public Integer getIsoversized() {
        return this.isoversized;
    }

    public void setIsoversized(Integer isoversized) {
        this.isoversized = isoversized;
    }

    public Integer getIspaper() {
        return this.ispaper;
    }

    public void setIspaper(Integer ispaper) {
        this.ispaper = ispaper;
    }

    public Integer getIspromo() {
        return this.ispromo;
    }

    public void setIspromo(Integer ispromo) {
        this.ispromo = ispromo;
    }

    public Integer getIsreprint() {
        return this.isreprint;
    }

    public void setIsreprint(Integer isreprint) {
        this.isreprint = isreprint;
    }

    public Integer getIsreserved() {
        return this.isreserved;
    }

    public void setIsreserved(Integer isreserved) {
        this.isreserved = isreserved;
    }

    public Integer getIsstarter() {
        return this.isstarter;
    }

    public void setIsstarter(Integer isstarter) {
        this.isstarter = isstarter;
    }

    public Integer getIsstoryspotlight() {
        return this.isstoryspotlight;
    }

    public void setIsstoryspotlight(Integer isstoryspotlight) {
        this.isstoryspotlight = isstoryspotlight;
    }

    public Integer getIstextless() {
        return this.istextless;
    }

    public void setIstextless(Integer istextless) {
        this.istextless = istextless;
    }

    public Integer getIstimeshifted() {
        return this.istimeshifted;
    }

    public void setIstimeshifted(Integer istimeshifted) {
        this.istimeshifted = istimeshifted;
    }

    public String getLayout() {
        return this.layout;
    }

    public void setLayout(String layout) {
        this.layout = layout;
    }

    public String getLeadershipskills() {
        return this.leadershipskills;
    }

    public void setLeadershipskills(String leadershipskills) {
        this.leadershipskills = leadershipskills;
    }

    public String getLife() {
        return this.life;
    }

    public void setLife(String life) {
        this.life = life;
    }

    public String getLoyalty() {
        return this.loyalty;
    }

    public void setLoyalty(String loyalty) {
        this.loyalty = loyalty;
    }

    public String getManacost() {
        return this.manacost;
    }

    public void setManacost(String manacost) {
        this.manacost = manacost;
    }

    public Integer getMcmid() {
        return this.mcmid;
    }

    public void setMcmid(Integer mcmid) {
        this.mcmid = mcmid;
    }

    public Integer getMcmmetaid() {
        return this.mcmmetaid;
    }

    public void setMcmmetaid(Integer mcmmetaid) {
        this.mcmmetaid = mcmmetaid;
    }

    public String getMcmname() {
        return this.mcmname;
    }

    public void setMcmname(String mcmname) {
        this.mcmname = mcmname;
    }

    public Integer getMtgarenaid() {
        return this.mtgarenaid;
    }

    public void setMtgarenaid(Integer mtgarenaid) {
        this.mtgarenaid = mtgarenaid;
    }

    public Integer getMtgofoilid() {
        return this.mtgofoilid;
    }

    public void setMtgofoilid(Integer mtgofoilid) {
        this.mtgofoilid = mtgofoilid;
    }

    public Integer getMtgoid() {
        return this.mtgoid;
    }

    public void setMtgoid(Integer mtgoid) {
        this.mtgoid = mtgoid;
    }

    public Integer getMtgstocksid() {
        return this.mtgstocksid;
    }

    public void setMtgstocksid(Integer mtgstocksid) {
        this.mtgstocksid = mtgstocksid;
    }

    public Integer getMultiverseid() {
        return this.multiverseid;
    }

    public void setMultiverseid(Integer multiverseid) {
        this.multiverseid = multiverseid;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getNames() {
        return this.names;
    }

    public void setNames(String names) {
        this.names = names;
    }

    public String getNumber() {
        return this.number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    public String getOriginaltext() {
        return this.originaltext;
    }

    public void setOriginaltext(String originaltext) {
        this.originaltext = originaltext;
    }

    public String getOriginaltype() {
        return this.originaltype;
    }

    public void setOriginaltype(String originaltype) {
        this.originaltype = originaltype;
    }

    public String getOtherfaceids() {
        return this.otherfaceids;
    }

    public void setOtherfaceids(String otherfaceids) {
        this.otherfaceids = otherfaceids;
    }

    public String getPower() {
        return this.power;
    }

    public void setPower(String power) {
        this.power = power;
    }

    public String getPrintings() {
        return this.printings;
    }

    public void setPrintings(String printings) {
        this.printings = printings;
    }

    public String getPurchaseurls() {
        return this.purchaseurls;
    }

    public void setPurchaseurls(String purchaseurls) {
        this.purchaseurls = purchaseurls;
    }

    public String getRarity() {
        return this.rarity;
    }

    public void setRarity(String rarity) {
        this.rarity = rarity;
    }

    public String getScryfallid() {
        return this.scryfallid;
    }

    public void setScryfallid(String scryfallid) {
        this.scryfallid = scryfallid;
    }

    public String getScryfallillustrationid() {
        return this.scryfallillustrationid;
    }

    public void setScryfallillustrationid(String scryfallillustrationid) {
        this.scryfallillustrationid = scryfallillustrationid;
    }

    public String getScryfalloracleid() {
        return this.scryfalloracleid;
    }

    public void setScryfalloracleid(String scryfalloracleid) {
        this.scryfalloracleid = scryfalloracleid;
    }

    public String getSetcode() {
        return this.setcode;
    }

    public void setSetcode(String setcode) {
        this.setcode = setcode;
    }

    public String getSide() {
        return this.side;
    }

    public void setSide(String side) {
        this.side = side;
    }

    public String getSubtypes() {
        return this.subtypes;
    }

    public void setSubtypes(String subtypes) {
        this.subtypes = subtypes;
    }

    public String getSupertypes() {
        return this.supertypes;
    }

    public void setSupertypes(String supertypes) {
        this.supertypes = supertypes;
    }

    public Integer getTcgplayerproductid() {
        return this.tcgplayerproductid;
    }

    public void setTcgplayerproductid(Integer tcgplayerproductid) {
        this.tcgplayerproductid = tcgplayerproductid;
    }

    public String getTcgplayerpurchaseurl() {
        return this.tcgplayerpurchaseurl;
    }

    public void setTcgplayerpurchaseurl(String tcgplayerpurchaseurl) {
        this.tcgplayerpurchaseurl = tcgplayerpurchaseurl;
    }

    public String getText() {
        return this.text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getToughness() {
        return this.toughness;
    }

    public void setToughness(String toughness) {
        this.toughness = toughness;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getTypes() {
        return this.types;
    }

    public void setTypes(String types) {
        this.types = types;
    }

    public String getUuid() {
        return this.uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public String getVariations() {
        return this.variations;
    }

    public void setVariations(String variations) {
        this.variations = variations;
    }

    public String getWatermark() {
        return this.watermark;
    }

    public void setWatermark(String watermark) {
        this.watermark = watermark;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Cards (");

        sb.append(id);
        sb.append(", ").append(artist);
        sb.append(", ").append(bordercolor);
        sb.append(", ").append(coloridentity);
        sb.append(", ").append(colorindicator);
        sb.append(", ").append(colors);
        sb.append(", ").append(convertedmanacost);
        sb.append(", ").append(dueldeck);
        sb.append(", ").append(edhrecrank);
        sb.append(", ").append(faceconvertedmanacost);
        sb.append(", ").append(flavortext);
        sb.append(", ").append(frameeffect);
        sb.append(", ").append(frameeffects);
        sb.append(", ").append(frameversion);
        sb.append(", ").append(hand);
        sb.append(", ").append(hasfoil);
        sb.append(", ").append(hasnodecklimit);
        sb.append(", ").append(hasnonfoil);
        sb.append(", ").append(isalternative);
        sb.append(", ").append(isarena);
        sb.append(", ").append(isfullart);
        sb.append(", ").append(ismtgo);
        sb.append(", ").append(isonlineonly);
        sb.append(", ").append(isoversized);
        sb.append(", ").append(ispaper);
        sb.append(", ").append(ispromo);
        sb.append(", ").append(isreprint);
        sb.append(", ").append(isreserved);
        sb.append(", ").append(isstarter);
        sb.append(", ").append(isstoryspotlight);
        sb.append(", ").append(istextless);
        sb.append(", ").append(istimeshifted);
        sb.append(", ").append(layout);
        sb.append(", ").append(leadershipskills);
        sb.append(", ").append(life);
        sb.append(", ").append(loyalty);
        sb.append(", ").append(manacost);
        sb.append(", ").append(mcmid);
        sb.append(", ").append(mcmmetaid);
        sb.append(", ").append(mcmname);
        sb.append(", ").append(mtgarenaid);
        sb.append(", ").append(mtgofoilid);
        sb.append(", ").append(mtgoid);
        sb.append(", ").append(mtgstocksid);
        sb.append(", ").append(multiverseid);
        sb.append(", ").append(name);
        sb.append(", ").append(names);
        sb.append(", ").append(number);
        sb.append(", ").append(originaltext);
        sb.append(", ").append(originaltype);
        sb.append(", ").append(otherfaceids);
        sb.append(", ").append(power);
        sb.append(", ").append(printings);
        sb.append(", ").append(purchaseurls);
        sb.append(", ").append(rarity);
        sb.append(", ").append(scryfallid);
        sb.append(", ").append(scryfallillustrationid);
        sb.append(", ").append(scryfalloracleid);
        sb.append(", ").append(setcode);
        sb.append(", ").append(side);
        sb.append(", ").append(subtypes);
        sb.append(", ").append(supertypes);
        sb.append(", ").append(tcgplayerproductid);
        sb.append(", ").append(tcgplayerpurchaseurl);
        sb.append(", ").append(text);
        sb.append(", ").append(toughness);
        sb.append(", ").append(type);
        sb.append(", ").append(types);
        sb.append(", ").append(uuid);
        sb.append(", ").append(variations);
        sb.append(", ").append(watermark);

        sb.append(")");
        return sb.toString();
    }
}
