/*
 * This file is generated by jOOQ.
 */
package com.mtgjson.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Rulings implements Serializable {

    private static final long serialVersionUID = 205310780;

    private Integer id;
    private String  date;
    private String  text;
    private String  uuid;

    public Rulings() {}

    public Rulings(Rulings value) {
        this.id = value.id;
        this.date = value.date;
        this.text = value.text;
        this.uuid = value.uuid;
    }

    public Rulings(
        Integer id,
        String  date,
        String  text,
        String  uuid
    ) {
        this.id = id;
        this.date = date;
        this.text = text;
        this.uuid = uuid;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getDate() {
        return this.date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getText() {
        return this.text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getUuid() {
        return this.uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Rulings (");

        sb.append(id);
        sb.append(", ").append(date);
        sb.append(", ").append(text);
        sb.append(", ").append(uuid);

        sb.append(")");
        return sb.toString();
    }
}
